# general settings
name: MSEResnet18_KonIQ10k  # 本次实验的名字
model_type: GeneralIQAModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123

# dataset and data loader settings
datasets:
  train:
    name: koniq10k
    type: GeneralNRDataset
    dataroot_target: /media/disk/lin/linpeng/code/IQA-PyTorch/datasets/koniq10k/1124
    meta_info_file: /media/disk/lin/linpeng/code/IQA-PyTorch/datasets/meta_info/meta_info_KonIQ10kDataset.csv
    split_file: /media/disk/lin/linpeng/code/IQA-PyTorch/datasets/meta_info/koniq10k_official.pkl

    augment:
      hflip: true
      random_crop: 224
    img_range: 1

    # data loader
    use_shuffle: true  # 这个参数没有用的地方，实际中是根据epoch设置的随机数种子进行采样的。
    num_worker_per_gpu: 16
    batch_size_per_gpu: 96
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    use_rank: true

  val:
    name: koniq10k
    type: GeneralNRDataset
    dataroot_target: /media/disk/lin/linpeng/code/IQA-PyTorch/datasets/koniq10k/1124
    meta_info_file: /media/disk/lin/linpeng/code/IQA-PyTorch/datasets/meta_info/meta_info_KonIQ10kDataset.csv
    split_file: /media/disk/lin/linpeng/code/IQA-PyTorch/datasets/meta_info/koniq10k_official.pkl

    num_worker_per_gpu: 4
    batch_size_per_gpu: 8

# network structures
network:
  type: Resnet
  model_name: resnet18
  pretrained: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim:
    type: Adam
    lr: !!float 1e-3
    weight_decay: !!float 5e-4

  scheduler:
    type: MultiStepLR
    milestones: [9125, 18250]
    gamma: 0.1

  total_iter: 27375 # 73 iter/epoch, about 375 epoch
  warmup_iter: -1  # no warm up

  # losses
  mos_loss_opt:
#    type: ListMonotonicSRCCLoss
#    loss_weight_PLCC: !!float 1.0
#    loss_weight_SRCC: !!float 1.0
    type: MSELoss
    loss_weight: !!float 1.0


# validation settings
val:
  val_freq: !!float 100
  save_img: false
  pbar: true

  key_metric: srcc # if this metric improve, update all metrics. If not specified, each best metric results will be updated separately
  metrics:
    srcc:
      type: calculate_srcc

    plcc:
      type: calculate_plcc

    krcc:
      type: calculate_krcc

# logging settings
logger:  # debug模式下，这些设置无效
  print_freq: 30
  save_checkpoint_freq: !!float 5e9
  save_latest_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500